name: Telegram Notify for New Pull Requests

on:
  repository_dispatch:
  pull_request:
    types: [opened]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: send custom message with args
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_GROUP_ID }}
        token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        args: ✅ New pull request received https://github.com/worldsnas/StarPlayer/pulls
