name: Telegram Notify for New Pull Requests

on:
  pull_request:
    types: [opened]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
#    - name: Dump GitHub context
#      env:
#        GITHUB_CONTEXT: ${{ toJson(github) }}
#      run:
#        echo "$GITHUB_CONTEXT"
    - name: Telegram Notify
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_GROUP_ID }}
        token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        message: |
          ✅ New Pull Request Received

          👉 ${{ github.event.pull_request._links.html.href }}

